project:
  name: Retranslator
  debug: true
  environment: development

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8080

metrics:
  host: 0.0.0.0
  port: 9200
  path: /metrics
  namespace: bss
  subsystem: office

jaeger:
  service: "bss-office-retranslator"
  host: "jaeger"
  port: ":6831"

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

database:
  host: postgres
  port: 5432
  user: docker
  password: docker
  name: bss_office_api
  sslmode: disable
  migrations: migrations
  driver: pgx

kafka:
  capacity: 512
  topic: "bss-office-events"
  groupId: "bss-office-api"
  brokers:
    - "localhost:9095"
    - "localhost:9096"
    - "localhost:9097"

telemetry:
  #graylogPath: graylog:12201 # docker-compose
  graylogPath: localhost:12201 #local

retranslator:
  channelsize: 512
  consumercount: 2
  consumesize: 10
  producercount: 28
  producertimeout: 1ms
  producerbatchsize: 10
  workercount: 2
  consumetimeout: 1ms